=== aksharsamir/Magento/etc/form_templates.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="form_templates" type="formsTemplate" />
				<xs:element minOccurs="1" maxOccurs="unbounded" name="page_templates" type="formsTemplate" />
				<xs:element minOccurs="1" maxOccurs="unbounded" name="field_templates" type="formsTemplate" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="formsTemplate">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="template" type="template" />
        </xs:sequence>
    </xs:complexType>
	<xs:complexType name="template">
        <xs:sequence>
            <xs:element name="name" />
            <xs:element name="file" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== aksharsamir/Magento/etc/form_templates.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="form_templates.xsd">
    <form_templates>
        <template>
            <name>Default</name>
            <file>form/default.phtml</file>
        </template>
    </form_templates>
	<page_templates>
		<template>
            <name>Default</name>
            <file>page/default.phtml</file>
        </template>
		<template>
            <name>Bootstrap columm 6</name>
            <file>page/bootstrap/col-6.phtml</file>
        </template>
		<template>
            <name>Bootstrap columm 4</name>
            <file>page/bootstrap/col-4.phtml</file>
        </template>
	</page_templates>
	<field_templates>
		<template>
            <name>Default</name>
            <file>field/default.phtml</file>
        </template>
		<template>
            <name>Bootstrap Row</name>
            <file>field/bootstrap/row.phtml</file>
        </template>
	</field_templates>
</config>
