=== aksharsamir/Magento/etc/form_validators.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="form_validators" type="formsValidator" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="formsValidator">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="validator" type="validator" />
        </xs:sequence>
    </xs:complexType>
	<xs:complexType name="validator">
        <xs:sequence>
            <xs:element name="name" />
            <xs:element name="class" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== aksharsamir/Magento/etc/form_validators.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="form_validators.xsd">
    <form_validators>
		<validator>
            <name>None</name>
            <class>Etailors\Forms\Helper\Validator\None</class>
        </validator>
        <validator>
            <name>Alphabetic</name>
            <class>Etailors\Forms\Helper\Validator\Alpha</class>
        </validator>
		<validator>
            <name>Alpha numeric</name>
            <class>Etailors\Forms\Helper\Validator\AlphaNum</class>
        </validator>
		<validator>
            <name>Numeric</name>
            <class>Etailors\Forms\Helper\Validator\Numeric</class>
        </validator>
		<validator>
            <name>Emailaddress</name>
            <class>Etailors\Forms\Helper\Validator\Email</class>
        </validator>
		<validator>
            <name>URL</name>
            <class>Etailors\Forms\Helper\Validator\Url</class>
        </validator>
    </form_validators>
</config>
